webtalk_init -webtalk_dir /home/hkamath3/gt-cs3220-spr21.github.io/assignment3_files/assignment3/assignment3.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar  4 17:22:53 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3fb403e6-e941-454f-9238-cc9e83088532" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d1c8f75c64624f14852b094271b671d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel Xeon E312xx (Sandy Bridge)" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2099.998 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "960 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "34 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "284" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "15" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "374900_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2534404635 -regid "" -xml /home/hkamath3/gt-cs3220-spr21.github.io/assignment3_files/assignment3/assignment3.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/hkamath3/gt-cs3220-spr21.github.io/assignment3_files/assignment3/assignment3.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/hkamath3/gt-cs3220-spr21.github.io/assignment3_files/assignment3/assignment3.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
